### ISSUE TITLE
Cancellation Signal is always null?

### ISSUE THREAD

**Issue by codingjeremy** [android/storage-samples#14]
<a href="https://github.com/anmolvermamm"><img src="https://avatars2.githubusercontent.com/u/32521663?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anmolvermamm](https://github.com/anmolvermamm)**
_Friday Sep 28, 2018 at 13:25 GMT_
_Originally opened as https://github.com/googlesamples/android-StorageProvider/issues/6_

----

https://github.com/googlesamples/android-StorageProvider/blob/6f21c5616efed8058b9759202ae1c09d2f124821/Application/src/main/java/com/example/android/storageprovider/MyCloudProvider.java#L296

I have an implementation of document provider, why is it that the cancellation signal is always null, when someone tries to opendocument from documentprovider ?

Thanks for your time!

**Comment by lukeisontheroad** [comment]
I do have the same question. I the signal passed to my openDocument method is always null, therefore I am not able to detect if a user canceled the request. @anmolvermamm did you get an answer?
