### ISSUE TITLE
How to parse APK using SAF ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#15]
It was possible before using file-path, but now I can't see of a way to do it, to get various APK information on the file system, such as app-icon and app-name:

https://developer.android.com/reference/android/content/pm/PackageManager.html#getPackageArchiveInfo(java.lang.String,%20int)

Forcing us to use SAF (on Q) instead of storage permission should also offer us alternatives to all of the Android framework functions.

**Comment by nic0lette** [comment]
Hi! Thanks for the feedback :)

I'm curious what the use case might be for opening a random APK on the filesystem might be (since there are places an app can place data to access them with file paths even when its used with scoped storage), but I actually think this discussion would be better had as an issue on the official Android issue tracker, either in the top [level component](https://issuetracker.google.com/issues?q=status:open%20componentid:190923) or in the [storage component](https://issuetracker.google.com/issues?q=status:open%20componentid:192805).

I think raising this concern there will allow better visibility to the engineering team to ensure your use case is being covered.

**Comment by AndroidDeveloperLB** [comment]
It's not " opening a random APK " . 
File manager apps and any app that can show information about APK files should be able to do it. Those files can be anywhere the user has put them.
They should be able to show the app name and its icon.
When opening, it could show extra information before really installing.

I can already see the impact of not being able to do it. An app called "Solid Explorer" ([here](https://play.google.com/store/apps/details?id=pl.solidexplorer2)) used to be able to show APK icons and also have a tool for APK, when choosing to open them. Now that it targets Android Q, both don't work at all. Not only that, but its searching capability became much slower because of using SAF instead of File-API. If you run the app on P and Q, you will notice it all.

Another example is my app ([here](https://play.google.com/store/apps/details?id=com.lb.app_manager)). Currently it target Android Q but because I don't see any way to overcome this (and because SAF is really the most terrible thing Google has made for Android, see [here](https://github.com/android/storage/issues/17#issuecomment-529606836)), I still use File API with the flag that allows me to do it. My app shows all APK files in a list, together with various information about each, including icon and app name. 

As for talking about it, I've already done it multiple times about various issues with SAF, from the beginning of Q beta 1 , and I added more and more variants as nobody from Google helped, and I've found more and more about how lacking SAF API truly is compared to File API :

- https://issuetracker.google.com/issues/139146342
- https://issuetracker.google.com/issues/134822100
- https://issuetracker.google.com/issues/135376205
- https://issuetracker.google.com/issues/134784560
- https://issuetracker.google.com/issues/137927543
- https://issuetracker.google.com/issues/137927542
- https://issuetracker.google.com/issues/137882014
- https://issuetracker.google.com/issues/137882015
- https://issuetracker.google.com/issues/134367310
- https://issuetracker.google.com/issues/134473341
- https://issuetracker.google.com/issues/134766817
- https://issuetracker.google.com/issues/137528497
- https://issuetracker.google.com/issues/135801445
- https://issuetracker.google.com/issues/137084501
- https://issuetracker.google.com/issues/134858951
- https://issuetracker.google.com/issues/136171427
- https://issuetracker.google.com/issues/135678934
- https://issuetracker.google.com/issues/135546735
- https://issuetracker.google.com/issues/135546722
- https://issuetracker.google.com/issues/134370342
- https://issuetracker.google.com/issues/134379739
- https://issuetracker.google.com/issues/132825438
- https://issuetracker.google.com/issues/132834983
- https://issuetracker.google.com/issues/132434082
- https://issuetracker.google.com/issues/129629193
- https://issuetracker.google.com/issues/131447175
- https://issuetracker.google.com/issues/132481545
- https://issuetracker.google.com/issues/133047170
-https://issuetracker.google.com/issues/131733663
- https://issuetracker.google.com/issues/132408120

Nobody from Google has helped about any of those, and even though there are countless of people against forcing us to use SAF instead of the standard File API (example [here](https://issuetracker.google.com/issues/128591846), which has a lot of links and got closed), Google didn't do anything about it, and just added a flag to delay the moving to SAF. It's not a solution. It's delaying of the problem.

What's so hard in making SAF grant access to files so that both File API and SAF API could work together?

Really. Just search the issue tracker and you will see how many developers hate this. It's not just there. It's also on reddit, [on XDA](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/), on various Android blog websites...
And SAF isn't even the only restriction on Q, as Q got plenty of those that [kill/ruin various apps](https://www.reddit.com/r/Android/comments/cv7afv/sunday_rantrage_aug_25_2019_your_weekly_complaint/ey3chbl/). Just search for SAF or scoped storage, and you will find plenty of developers talking about it.

There was even a bug report about [how slow SAF is compared to File-API](https://issuetracker.google.com/issues/130261278) (to me it's x3-x4 slower, and for others it's even worse), and it was marked as "fixed" even though it stayed in the same performance.

**Comment by nic0lette** [comment]
I appreciate the feedback, and have shared it with engineers working on SAF.

That being said, since this sample doesn't address how to work with APK files at the moment, and since it's not in scope for these samples, I'm going to close this issue.

I understand that it may feel frustrating, but the best place to share this feedback is on those issues that you linked.

Thank you for all your help identifying issues with our sample code. It's appreciated.

**Comment by AndroidDeveloperLB** [comment]
@nic0lette I hope they will listen. I'm really out of options.
Sadly you say it's the best place, but it's not good enough, because I already wrote all of these before Q became public, and none were handled. Now developers and users will have to take the penalty. Bad UX, bad performance, no backward compatibility, no support for libraries, nothing good out of it.
