### ISSUE TITLE
Bug: "StorageClient" sample doesn't show its entire text 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#18]
You can't scroll here:

![image](https://user-images.githubusercontent.com/5357526/64481229-870a7600-d1e0-11e9-9d32-e3a621b31bcc.png)

**Comment by nic0lette** [comment]
I think this was fixed by #23

**Comment by AndroidDeveloperLB** [comment]
Seems fixed, but it still has some issues being shown: it has weird empty spaces in various places in the text:

![image](https://user-images.githubusercontent.com/5357526/65533487-617eab80-df06-11e9-9d11-ef6d7f469905.png)

![image](https://user-images.githubusercontent.com/5357526/65533529-79562f80-df06-11e9-8f68-ba4335e8de7f.png)

**Comment by AndroidDeveloperLB** [comment]
And also above the "Ready" for some reason.

**Comment by nic0lette** [comment]
The "Ready" text is still probably off, but hopefully the rest of the text flows better following #31

**Comment by AndroidDeveloperLB** [comment]
Is it available?

**Comment by nic0lette** [comment]
I hope it's fixed in master now? If it's not, please let me know?

**Comment by AndroidDeveloperLB** [comment]
Ummm... Now I see nothing at the bottom:

![image](https://user-images.githubusercontent.com/5357526/65714807-827d0300-e0a4-11e9-9564-486f896ca0ca.png)

**Comment by nic0lette** [comment]
I can't repro that @AndroidDeveloperLB =( What device/OS version?

**Comment by AndroidDeveloperLB** [comment]
@nic0lette Pixel 2 Q.
Dark theme enabled.
With it disabled, I can see the text, but still has empty line in beginning.
