### ISSUE TITLE
"android-DirectShare " sample missing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#38]
This repository was archived:

https://github.com/googlearchive/android-DirectShare

 and the only link it says it moved to is here, but I don't see any sample of it here.
Also, there was a rumor that Google works on a new sharing technique of files, that will replace Android-Beam. Maybe it's a good idea to show how to use it here too?

**Comment by volkansahin45** [comment]
I thinks this repo is android-DirectShare it's also mentioned in archived repo's readme 
https://github.com/android/storage-samples/tree/master/SharingShortcuts

**Comment by AndroidDeveloperLB** [comment]
I don't know.

**Comment by volkansahin45** [comment]
@nic0lette Can you look at this issue and take an action?

**Comment by nic0lette** [comment]
@volkansahin45 is correct, https://github.com/android/storage-samples/tree/master/SharingShortcuts is the new location/name for the android-DirectShare sample.

**Comment by AndroidDeveloperLB** [comment]
@nic0lette Why the change of the name ?
And why from "DirectShare " to "SharingShortcuts" ? 
It doesn't share any shortcuts. It just shares some text...
