### ISSUE TITLE
Bug: Sample "ContentProviderPagingKotlin" still crashes, this time by just scrolling

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#43]
See here:
https://github.com/android/storage-samples/issues/16#issuecomment-549250814

**Comment by volkansahin45** [comment]
Is there any problem now?

**Comment by nic0lette** [comment]
I haven't been able to reproduce this. If you still can, please add a stack trace, since that will be more helpful in debugging than the video. Thank you!
