### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by swapnil-musale** [android/storage-samples#53]
Use case - Currently I'm working on video uploading module. To get the video i have fired SFA video picker intent but I can't get any way or code to get the video details from uri in OnActivityResult even i have watched Google IO 19 Preparing Scoped Storage Video but there also not provided any sample code how to do that. ( Video details mean duration size name resolution and name )

To get the video details we have to use MediaStore api which recommended one and MediaStore only works with content URIs if i pass file uri then cursor will be always null 
and we only get the content uri when cursor isnot null 

Hoping to will answer my question someone

**Comment by nic0lette** [comment]
You should be able to read the exif information in the video file using the [ExifInterface](https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface) in AndroidX.

Open the URI you get back with the `ContentResolver#openFileDescriptor ` and pass that into the constructor.
