### ISSUE TITLE
FileManager can't open selected files by intent action

### ISSUE THREAD

**Issue by mirwisek** [android/storage-samples#61]
I've been following latest documentation and tried to open the files after all permissions check mentioned in the docs. I thought I might be missing something, ergo, after checking the FileManager sample, it seems `openFile()` extension from FileManager sample is also helpless in opening the file. I tried to open a word file (.docx) an image file, a pdf file. It opens the app but the file can't be found and (Adobe Reader, Word and Gallery shows the main screen).

Tested with Realme 5 Pro (Android 10) with all permissions granted

```
fun openFile(activity: AppCompatActivity, selectedItem: File) {
    // Get URI and MIME type of file
    val uri = Uri.fromFile(selectedItem).normalizeScheme()
    val mime: String = getMimeType(uri.toString())

    // Open file with user selected app
    val intent = Intent()
    intent.action = Intent.ACTION_VIEW
    intent.data = uri
    intent.type = mime
    return activity.startActivity(intent)
}
```

**Comment by cketti** [comment]
I'd say this is a bug. `FileProvider` or something similar should be used when launching external apps to open content. Passing `file:` URIs to other apps is rather unlikely to work in 2020.

**Comment by mirwisek** [comment]
Could you suggest how to format the URI so that it can be opened by apps. I couldn't find any latest solutions
