### ISSUE TITLE
Files copied by using Files.copy are not displayed in Gallery

### ISSUE THREAD

**Issue by tingreavinash** [android/storage-samples#88]
I am using `Files.copy` API (Package: `java.nio.file`) for copying images to new directory. The operation is working fine and I can see files are copied properly in new directory. But those newly copied files are not visible in Gallery by default.

If if use default file manager and try to move those newly copied files again in new folder then that new folder is immediately visible in phone gallery.

Do I need any change here? or I am missing something ?

**Code snippet which I am using:**

```java
for (Path srcPath : sourcePaths) {
                String fileName = srcPath.getFileName().toString();
                File targetFile = new File(SDCARD_PATH + TARGET_PATH + fileName);


                if (!fileName.equalsIgnoreCase(".nomedia") && !targetFile.exists()) {
                    Files.copy(srcPath, targetFile.toPath(), StandardCopyOption.COPY_ATTRIBUTES);
                }
            }
```

**Comment by yrezgui** [comment]
Hi @tingreavinash,
Can you tell me which SDK your app is targeting and which device SDK are you seeing this problem?

**Comment by tingreavinash** [comment]
Hi @yrezgui 

Thanks for your attention. My phone is on SDK 29, I am targeting SDK 28. However, The issue is solved now.

Problem was, I wansn't triggering MediaScan after copy operation. After I have triggered MediaScan after my operation is completed, then the latest files are automatically displayed in Phone Gallery.

**Solution Thread :** [Query posted on StackOverFlow](https://stackoverflow.com/questions/66988613/solved-files-copied-using-files-copy-api-are-not-visible-in-gallery/66988890?noredirect=1#comment118418416_66988890)

😃

**Comment by yrezgui** [comment]
That's what I was gonna suggest you. Previously, you had to trigger the MediaScanner manually. From Android 11, it's done automatically

**Comment by tingreavinash** [comment]
Thanks for the clarification and time! Closing the issue as the problem is resolved.
