### ISSUE TITLE
request for information regarding super user in android

### ISSUE THREAD

**Issue by Adeesh2411** [android/storage-samples#89]
I have android device which is rooted. I need to perform **Runtime.getRuntime().exec("su")** .and I have added READ_LOGs permission in manifest also. But even though i have root device its still gives me access denied. I have seen most of the blogs still the issue remains same. Can you please tell me  Is there anything missing here

**Comment by yrezgui** [comment]
Hi @Adeesh2411, your issue isn't related to this repository.
I don't have an answer to the issue you're facing as we're not recommending to have aroot access on your device. This blog post may bring you more information on the restriction you're facing: https://commonsware.com/blog/2012/07/12/read-logs-regression.html
